#!/usr/bin/env python

import sys
from fsirun import *

# Get level
if len(sys.argv) < 2:
    print "Usage: run_test_level n [init]"
    sys.exit(1)
level = int(sys.argv[1])

# Set common parameters
p = default_parameters()
p["uniform_timestep"] = True
p["initial_timestep"] = 0.05
p["num_initial_refinements"] = level
p["fixedpoint_tolerance"] = 1e-12
p["structure_element_degree"] = 1
p["max_num_refinements"] = 0

# Initialize data
if len(sys.argv) > 2 and sys.argv[2] == "init":
    p["solve_primal"] = True
    p["solve_dual"] = True
    p["estimate_error"] = False
else:
    p["solve_primal"] = False
    p["solve_dual"] = False
    p["estimate_error"] = True

# Choose problem
problem = "channel_with_flap"

run_local(problem, parameters=p, case=("level_%d" % level))
