rm -rf bin
rm -rf pvd
rm -rf adaptivity/*.xml
rm -rf adaptivity/no_iterations.txt
rm -rf adaptivity/fsi_tolerance.txt
rm -rf adaptivity/goal_functional.txt
rm -rf adaptivity/timesteps.txt
rm -rf adaptivity/M_ave.txt
rm -rf adaptivity/num_dofs.txt
rm -rf adaptivity/error_estimates.txt
rm -rf adaptivity/adaptivity.log
rm -rf adaptivity/uniform_timestep_dofs.txt
rm -rf adaptivity/timestep_hmin.txt
rm -rf adaptivity/pvd/*.vtu
rm -rf adaptivity/pvd/*.pvd
