rm -r bin
rm -r pvd
rm -r adaptivity/*.xml
rm -r adaptivity/no_iterations.txt
rm -r adaptivity/fsi_tolerance.txt
rm -r adaptivity/goal_functional.txt
rm -r adaptivity/timesteps.txt
rm -r adaptivity/M_ave.txt
rm -r adaptivity/num_dofs.txt
rm -r adaptivity/error_estimates.txt
rm -r adaptivity/adaptivity.log
rm -r adaptivity/pvd/*.vtu
rm -r adaptivity/pvd/*.pvd
rm -r *.pvd
rm -r *.vtu
